package br.scrumban.entity;

// Generated 26/07/2012 21:32:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FalhaLogin generated by hbm2java
 */
@Entity
@Table(name = "FalhaLogin", schema = "dbo", catalog = "dojoJava")
public class FalhaLogin implements java.io.Serializable {

	@Id
	@Column(name = "falhaLogin_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int falhaLoginId;
	
	@Column(name = "usuario_id", nullable = false)
	private int usuarioId;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataOcorrencia", length = 23)
	private Date dataOcorrencia;

	public FalhaLogin() {
	}

	public FalhaLogin(int falhaLoginId, int usuarioId) {
		this.falhaLoginId = falhaLoginId;
		this.usuarioId = usuarioId;
	}

	public FalhaLogin(int falhaLoginId, int usuarioId, Date dataOcorrencia) {
		this.falhaLoginId = falhaLoginId;
		this.usuarioId = usuarioId;
		this.dataOcorrencia = dataOcorrencia;
	}

	
	public int getFalhaLoginId() {
		return this.falhaLoginId;
	}

	public void setFalhaLoginId(int falhaLoginId) {
		this.falhaLoginId = falhaLoginId;
	}

	
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Date getDataOcorrencia() {
		return this.dataOcorrencia;
	}

	public void setDataOcorrencia(Date dataOcorrencia) {
		this.dataOcorrencia = dataOcorrencia;
	}

}
