package br.scrumban.entity;

// Generated 26/07/2012 21:32:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SucessoLogin generated by hbm2java
 */
@Entity
@Table(name = "SucessoLogin", schema = "dbo", catalog = "dojoJava")
public class SucessoLogin implements java.io.Serializable {

	@Id
	@Column(name = "SucessoLogin_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int sucessoLoginId;


	@Column(name = "usuario_id", nullable = false)
	private int usuarioId;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataLogin", length = 23)
	private Date dataLogin;

	public SucessoLogin() {
	}

	public SucessoLogin(int sucessoLoginId, int usuarioId) {
		this.sucessoLoginId = sucessoLoginId;
		this.usuarioId = usuarioId;
	}

	public SucessoLogin(int sucessoLoginId, int usuarioId, Date dataLogin) {
		this.sucessoLoginId = sucessoLoginId;
		this.usuarioId = usuarioId;
		this.dataLogin = dataLogin;
	}

	
	public int getSucessoLoginId() {
		return this.sucessoLoginId;
	}

	public void setSucessoLoginId(int sucessoLoginId) {
		this.sucessoLoginId = sucessoLoginId;
	}

	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Date getDataLogin() {
		return this.dataLogin;
	}

	public void setDataLogin(Date dataLogin) {
		this.dataLogin = dataLogin;
	}

}
