package br.scrumban.entity;

// Generated 26/07/2012 21:32:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "dbo", catalog = "dojoJava")
public class Usuario implements java.io.Serializable {

	@Id
	@Column(name = "usuario_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int usuarioId;

	@Column(name = "login", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)	
	private String login;
	
	@Column(name = "senha", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	private String senha;

	public Usuario() {
	}

	public Usuario(int usuarioId, String login, String senha) {
		this.usuarioId = usuarioId;
		this.login = login;
		this.senha = senha;
	}

	
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}
